version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 3s
      timeout: 3s
      retries: 5

  redis:
    image: redis:6.2.4-alpine
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 3s
      retries: 5     

  telegram:
    build: .
    command: bash -c "python telegram_main.py"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: db
      PORT: 5432
      REDIS_URL: redis://redis:6379/0

  server:
    build: .
    command: bash -c "uvicorn main:app --reload --port 8000 --host 0.0.0.0"
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: db
      PORT: 5432
      REDIS_URL: redis://redis:6379/0


volumes:
  pg_data:

